### ISSUE TITLE
Add a Makefile

### ISSUE THREAD

**Issue by sl** [bits-and-bots/lessons#1]
Having a Makefile to compile all the latex lessons and generate pdfs in a single folder would be awesome. It would also mean that to read the documents, all you'd have to do is `git clone <> & make`, which is great.

**Comment by drassaby** [comment]
Great idea 👍, do you wanna make it? If not, I could :)

**Comment by drassaby** [comment]
Oh, could you add to the README in the same PR too for instructions on using the Makefile?
