### ISSUE TITLE
Dancing Lesson

### ISSUE THREAD

**Issue by drassaby** [bits-and-bots/lessons#9]
We want to look into either a new lesson for moving the robots using dancing as an objective or consider using it to add goals to an old movement lesson. This is a good 'bring together what you've learned' lesson
- Have the robot perform some moves of the ChaCha Slide (or equivalent song)
- Have the students have a dance competition at the end with the robots

**Comment by verdabursal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Robot dance party lesson](https://trello.com/c/NRkbwx4t/69-robot-dance-party-lesson)
